<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Rudra-Heart" name="com.appium.tests.ProductTests" tests="4" failures="1" timestamp="2023-06-01T10:11:14 IST" time="73.796" errors="0">
  <testcase name="validateProductOnProductsPage" time="12.787" classname="com.appium.tests.ProductTests">
    <skipped/>
  </testcase> <!-- validateProductOnProductsPage -->
  <system-out/>
  <testcase name="validateProductOnProductDetailsPage" time="22.585" classname="com.appium.tests.ProductTests"/>
  <system-out/>
  <testcase name="validateProductOnProductDetailsPage" time="24.394" classname="com.appium.tests.ProductTests">
    <skipped/>
  </testcase> <!-- validateProductOnProductDetailsPage -->
  <system-out/>
  <testcase name="validateProductOnProductsPage" time="14.030" classname="com.appium.tests.ProductTests">
    <failure type="java.lang.AssertionError" message="*******************************Failing intentionally">
      <![CDATA[java.lang.AssertionError: *******************************Failing intentionally
at org.testng.Assert.fail(Assert.java:99)
at com.appium.tests.ProductTests.validateProductOnProductsPage(ProductTests.java:115)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateProductOnProductsPage -->
  <system-out/>
</testsuite> <!-- com.appium.tests.ProductTests -->
